package newVnt;

import estructuras.Nodo;
import estructuras.TablaHash;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author David Vergara
 */
public final class JOptionAddPersona extends java.awt.Dialog
{

    String nombrePersona = null;
    boolean validPersona = false;
    Nodo raiz = null;
    TablaHash tablaDePersonas = null;

    /**
     * Creates new form NewDialogGrupo
     * @param parent
     * @param modal
     * @param raiz
     */
    public JOptionAddPersona(java.awt.Frame parent, boolean modal, Nodo raiz)
    {
        super(parent, modal);
        initComponents();
        this.raiz = raiz;

        cargaTablaHash();
        System.out.println("Tablas en busqueda:\n");
        tablaDePersonas.verarboles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtNameRojoPersona = new javax.swing.JTextField();
        txtNormalColor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNombrePersona = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();

        txtNameRojoPersona.setText("jTextField1");
        txtNameRojoPersona.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51)));

        txtNormalColor.setText("jTextField1");
        txtNormalColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(174, 192, 124));

        txtNombrePersona.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNombrePersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombrePersona.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombrePersonaActionPerformed(evt);
            }
        });
        txtNombrePersona.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombrePersonaKeyPressed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar persona");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("¡Escribe el nombre del persona!");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setText("¡Escribe el apellido de la persona!");

        txtApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApellido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtApellidoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombrePersona)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(txtApellido)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAgregar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        if (txtNombrePersona.getText().trim().length() > 2)
        {
            txtNombrePersona.setBorder(txtNormalColor.getBorder());
            if (txtApellido.getText().trim().length() > 2)
            {
                String aux = txtNombrePersona.getText().trim() + " " + txtApellido.getText().trim();
                System.out.println(aux);
                String posibleName[] = tablaDePersonas.buscarDTS(aux);
                if (posibleName.length == 0)
                {
                    txtApellido.setBorder(txtNormalColor.getBorder());
                    nombrePersona = txtNombrePersona.getText().trim() + " " + txtApellido.getText().trim();
                    validPersona = true;
                    dispose();
                }
                for (int i = 0; i < posibleName.length; i++)
                {
                    if (posibleName[i].equals(aux))
                    {
                        System.out.println("El nombre ya existe");
                        JOptionPane.showMessageDialog(this, "El nombre ya existe");
                        txtNombrePersona.setBorder(txtNameRojoPersona.getBorder());
                        txtApellido.setBorder(txtNameRojoPersona.getBorder());
                        txtNombrePersona.requestFocus();
                        break;
                    }
                }
            } else
            {
                txtApellido.setBorder(txtNameRojoPersona.getBorder());
            }
        } else
        {
            txtNombrePersona.setBorder(txtNameRojoPersona.getBorder());
            txtApellido.setBorder(txtNameRojoPersona.getBorder());
        }
        guardaMultilista();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombrePersonaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombrePersonaActionPerformed
    {//GEN-HEADEREND:event_txtNombrePersonaActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        txtApellido.requestFocus();
    }//GEN-LAST:event_txtNombrePersonaActionPerformed

    private void txtNombrePersonaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombrePersonaKeyPressed
    {//GEN-HEADEREND:event_txtNombrePersonaKeyPressed
        if (txtNombrePersona.getText().trim().length() > 2)
        {
            txtNombrePersona.setBorder(txtNormalColor.getBorder());
        }

        
    }//GEN-LAST:event_txtNombrePersonaKeyPressed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtApellidoActionPerformed
    {//GEN-HEADEREND:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApellidoKeyPressed
    {//GEN-HEADEREND:event_txtApellidoKeyPressed
        if (txtApellido.getText().trim().length() > 2)
        {
            txtApellido.setBorder(txtNormalColor.getBorder());
        }
        if (evt.getKeyChar() == '\n')
        {
            btnAgregarActionPerformed(null);
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    public String getNombrePersona()
    {
        return this.nombrePersona;
    }

    public boolean isValidPersona()
    {
        return this.validPersona;
    }
    public void guardaMultilista()
    {
        try
        {
            try (ObjectOutputStream file = new ObjectOutputStream(new FileOutputStream("Archivos/raiz.dat"))) {
                file.writeObject(raiz);
            }
            System.out.println("Archivito guardadito xd");
        } catch (IOException ex)
        {
            System.out.println("No se encontro archivo");
        }
    }

    public void cargaTablaHash()
    {
        try
        {
            try (ObjectInputStream file = new ObjectInputStream(new FileInputStream("Archivos/Tabla.dat"))) {
                tablaDePersonas = (TablaHash) file.readObject();
            }
            if (tablaDePersonas != null)
            {
                TablaHash t = new TablaHash();
                t.verarboles();
            }
        } catch (ClassNotFoundException ex)
        {
            System.out.println("La clase no existe o diferente");
        } catch (IOException e)
        {
            System.out.println("No existe el archivo");
            tablaDePersonas = new TablaHash();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNameRojoPersona;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNormalColor;
    // End of variables declaration//GEN-END:variables
}
