/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeWhats;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cola.ColaD;
import estructuras.Multilista;
import estructuras.Nodo;
import java.awt.Cursor;
import newVnt.VtnAddMensaje;
import pila.PilaD;

/**
 *
 * @author David Vergara
 */
public class InterWhats extends javax.swing.JFrame
{

    PilaD pila1 = null;
    PilaD pila2 = null;
    ColaD cola = null;
    String s="";
    Datos alma = null;

    Nodo raizMensaje = null;
    Nodo raiz = null;
    String seleccionado = null, seleccionadoAnteriorPersona = null, seleccionadoAnteriorGrupo = null;

    /**
     * Creates new form InterWhats
     * @param raiz
     * @param seleccionadoMesnaje
     * @param seleccionadoAnteriorPersona
     * @param seleccionadoAnteriorGrupo
     */
    public InterWhats(Nodo raiz, String seleccionadoMesnaje, String seleccionadoAnteriorPersona, String seleccionadoAnteriorGrupo)
    {
        initComponents();

        jLabelP2.setText(seleccionadoAnteriorPersona);
        jLabelMensaje.setText("Grupo:"+seleccionadoAnteriorGrupo+" ➟ Persona: "+seleccionadoAnteriorPersona+"➟ Dia: "+ seleccionadoMesnaje);
        this.raiz=raiz;
        this.seleccionado = seleccionadoMesnaje;
        this.seleccionadoAnteriorPersona = seleccionadoAnteriorPersona;
        this.seleccionadoAnteriorGrupo = seleccionadoAnteriorGrupo;
        this.raizMensaje = Multilista.busca(Multilista.busca(Multilista.busca(raiz, seleccionadoAnteriorGrupo).getAbj(), seleccionadoAnteriorPersona).getAbj(), seleccionadoMesnaje);
        this.alma = (Datos) raizMensaje.getObj();
        Object carga;
        carga = ManipulaArchivos.carga("Archivos/Chat.dat");

        if (alma != null)
        {
            System.out.println("Alma no esta vacia");
            pila1 = alma.getPila1();
            pila2 = alma.getPila2();
            cola = alma.getCola();
            System.out.println("cola vacia?: "+cola.imprimir());
            aMensaje.setText(cola.imprimir());
        } else
        {
            System.out.println("alma esta vacia");
            alma = new Datos();
            pila1 = new PilaD();
            pila2 = new PilaD();
            cola = new ColaD();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnEnviarP1 = new javax.swing.JButton();
        btnEnviarP2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelP2 = new javax.swing.JLabel();
        TxtPersona1 = new javax.swing.JTextField();
        TxtPersona2 = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        btnMostrarChat = new javax.swing.JButton();
        btnBuscarP1 = new javax.swing.JButton();
        btnMostrarP1 = new javax.swing.JButton();
        btnBuscarP2 = new javax.swing.JButton();
        btnMostrarP2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aMensaje = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Whats");
        setBackground(new java.awt.Color(102, 255, 204));
        setUndecorated(true);

        btnEnviarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/enviar.png"))); // NOI18N
        btnEnviarP1.setText("Enviar");
        btnEnviarP1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnviarP1ActionPerformed(evt);
            }
        });

        btnEnviarP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/enviar.png"))); // NOI18N
        btnEnviarP2.setText("  Enviar");
        btnEnviarP2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnviarP2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YO");

        jLabelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP2.setText("Persona");

        TxtPersona1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TxtPersona1ActionPerformed(evt);
            }
        });
        TxtPersona1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                TxtPersona1KeyPressed(evt);
            }
        });

        TxtPersona2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TxtPersona2ActionPerformed(evt);
            }
        });
        TxtPersona2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                TxtPersona2KeyPressed(evt);
            }
        });

        btnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ordenarchat.png"))); // NOI18N
        btnOrdenar.setText("  Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnMostrarChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/chatMostar.png"))); // NOI18N
        btnMostrarChat.setText("  Mostrar Chat");
        btnMostrarChat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMostrarChatActionPerformed(evt);
            }
        });

        btnBuscarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarP1.setText("   Buscar");
        btnBuscarP1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarP1ActionPerformed(evt);
            }
        });

        btnMostrarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mostar.png"))); // NOI18N
        btnMostrarP1.setText("   Mostrar");
        btnMostrarP1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMostrarP1ActionPerformed(evt);
            }
        });

        btnBuscarP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarP2.setText("  Buscar");
        btnBuscarP2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarP2ActionPerformed(evt);
            }
        });

        btnMostrarP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mostar.png"))); // NOI18N
        btnMostrarP2.setText("  Mostrar");
        btnMostrarP2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMostrarP2ActionPerformed(evt);
            }
        });

        aMensaje.setEditable(false);
        aMensaje.setColumns(20);
        aMensaje.setLineWrap(true);
        aMensaje.setRows(5);
        aMensaje.setWrapStyleWord(true);
        jScrollPane1.setViewportView(aMensaje);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ExitChat.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });

        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtPersona1)
                            .addComponent(btnEnviarP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtPersona2)
                                .addComponent(btnEnviarP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarP2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnMostrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEnviarP1)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarP1)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrarP1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSalir)
                                .addGap(46, 46, 46)
                                .addComponent(jLabelP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEnviarP2)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarP2)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrarP2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenar)
                    .addComponent(btnMostrarChat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarP1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnviarP1ActionPerformed
    {//GEN-HEADEREND:event_btnEnviarP1ActionPerformed
        //aqui guardara en la pila
        this.setCursor(Cursor.WAIT_CURSOR);
        if (TxtPersona1.getText().trim().length() > 0)
        {
            String cad = TxtPersona1.getText().trim();

            pila1.insertar("<Yo>  " + cad);
            cola.insertar("<Yo>  " + cad);

            s = cola.imprimir();
            System.out.println(s);
            aMensaje.setText(s);
            CtrlInterfaz.limpia(TxtPersona1);
        } else
        {
            Mensaje.error(this, "No puedes enviar un mensaje en blanco");
        }

        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnEnviarP1ActionPerformed

    private void btnEnviarP2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnviarP2ActionPerformed
    {//GEN-HEADEREND:event_btnEnviarP2ActionPerformed
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        if (TxtPersona2.getText().trim().length() > 0)
        {
            String cad2 = TxtPersona2.getText().trim();
            pila2.insertar("                                                                                                                     <"
                    +seleccionadoAnteriorPersona+">  " + cad2);
            cola.insertar("                                                                                                                      <"
                    +seleccionadoAnteriorPersona+">  " + cad2);

            s = cola.imprimir();
            System.out.println(s);
            aMensaje.setText(s);
            CtrlInterfaz.limpia(TxtPersona2);
        } else
        {

            Mensaje.error(this, "No puedes enviar un mensaje en blanco");
        }
        this.setCursor(Cursor.DEFAULT_CURSOR);

    }//GEN-LAST:event_btnEnviarP2ActionPerformed

    private void TxtPersona1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxtPersona1ActionPerformed
    {//GEN-HEADEREND:event_TxtPersona1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtPersona1ActionPerformed

    private void TxtPersona2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxtPersona2ActionPerformed
    {//GEN-HEADEREND:event_TxtPersona2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPersona2ActionPerformed

    private void TxtPersona1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TxtPersona1KeyPressed
    {//GEN-HEADEREND:event_TxtPersona1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            btnEnviarP1ActionPerformed(null);
        }
    }//GEN-LAST:event_TxtPersona1KeyPressed

    private void TxtPersona2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TxtPersona2KeyPressed
    {//GEN-HEADEREND:event_TxtPersona2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            btnEnviarP2ActionPerformed(null);
        }
    }//GEN-LAST:event_TxtPersona2KeyPressed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOrdenarActionPerformed
    {//GEN-HEADEREND:event_btnOrdenarActionPerformed
        cola.Nodo n = cola.getFrente();
        ColaD c = new ColaD();
        PilaD p1 = new PilaD();
        PilaD p2 = new PilaD();
        while (n != null)
        {
            c.insertar(n.getDato());
            n = n.getSig();
        }
        //Ordenala ColaD c
        p1.insertar(c.eliminar());
        if (c.getFrente() == null)
        {
            c.insertar(p1.eliminar());
        } else
        {
            while (c.getFrente() != null)
            {
                if (String.valueOf(c.getFrente().getDato()).compareTo(String.valueOf(p1.getTope().getDato())) < 0)
                {
                    p1.insertar(c.eliminar());
                } else
                {
                    while (p1.getTope() != null && String.valueOf(c.getFrente().getDato()).compareTo(String.valueOf(p1.getTope().getDato())) > 0)
                    {
                        p2.insertar(p1.eliminar());
                    }
                    p1.insertar(c.eliminar());
                }
                while (p2.getTope() != null)
                {
                    p1.insertar(p2.eliminar());
                }
            }
        }
        while (p1.getTope() != null)
        {
            c.insertar(p1.eliminar());
        }
        aMensaje.setText(c.imprimir() + p1.imprimir() + p2.imprimir());
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnMostrarChatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarChatActionPerformed
    {//GEN-HEADEREND:event_btnMostrarChatActionPerformed
        s = cola.imprimir();
        aMensaje.setText(s);
    }//GEN-LAST:event_btnMostrarChatActionPerformed

    private void btnBuscarP1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarP1ActionPerformed
    {//GEN-HEADEREND:event_btnBuscarP1ActionPerformed
        if (!(TxtPersona1.getText().isEmpty()))
        {
            s = pila1.buscar(TxtPersona1.getText());
            aMensaje.setText(s);
        } else
        {
            Mensaje.error(this, "No hay nada que buscar, Escribe en la barra para buscar");
        }
    }//GEN-LAST:event_btnBuscarP1ActionPerformed

    private void btnBuscarP2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarP2ActionPerformed
    {//GEN-HEADEREND:event_btnBuscarP2ActionPerformed
        if (!(TxtPersona2.getText().isEmpty()))
        {
            s = pila2.buscar(TxtPersona2.getText());
            aMensaje.setText(s);
        } else
        {
            Mensaje.error(this, "No hay nada que buscar, Escribe en la barra para buscar");
        }
    }//GEN-LAST:event_btnBuscarP2ActionPerformed

    private void btnMostrarP1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarP1ActionPerformed
    {//GEN-HEADEREND:event_btnMostrarP1ActionPerformed
        aMensaje.setText(pila1.imprimir());
    }//GEN-LAST:event_btnMostrarP1ActionPerformed

    private void btnMostrarP2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarP2ActionPerformed
    {//GEN-HEADEREND:event_btnMostrarP2ActionPerformed
        aMensaje.setText(pila2.imprimir());
    }//GEN-LAST:event_btnMostrarP2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        String etqs[] = new String[3];
        etqs[0] = seleccionadoAnteriorGrupo;
        etqs[1] = seleccionadoAnteriorPersona;
        etqs[2] = seleccionado;
        System.out.println("antes de insertal el mensaje:\n"+Multilista.prb(raiz));
        raiz = Multilista.insertaMensaje(raiz, 0, etqs, alma);
        System.out.println("Despues de insertar el mensaje:\n"+Multilista.prb(raiz));
        Datos d = (Datos)(Multilista.busca(Multilista.busca(Multilista.busca(raiz, seleccionadoAnteriorGrupo).getAbj(),
                seleccionadoAnteriorPersona).getAbj(), seleccionado).getObj());
        VtnAddMensaje mensaje = new VtnAddMensaje(raiz, seleccionadoAnteriorPersona, seleccionadoAnteriorGrupo);        
        ManipulaArchivos.guarda(d, "Archivos/Chat.dat");
        System.out.println("Holaaaaaaaaaaasdfendasklfghndfkljgnbkjladsfbglkjdfbgkjlbdfalkjgblkd;fajgblkjdfbglkjdf");
        mensaje.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtPersona1;
    private javax.swing.JTextField TxtPersona2;
    private javax.swing.JTextArea aMensaje;
    private javax.swing.JButton btnBuscarP1;
    private javax.swing.JButton btnBuscarP2;
    private javax.swing.JButton btnEnviarP1;
    private javax.swing.JButton btnEnviarP2;
    private javax.swing.JButton btnMostrarChat;
    private javax.swing.JButton btnMostrarP1;
    private javax.swing.JButton btnMostrarP2;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelP2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
